version: '3'

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16

services:

  nats:
    container_name: cn_nats
    image: nats:1.4.1
    ports:
      - 54222:4222
      - 58222:8222
    networks:
      - default

